services:

  backend:     
    build:
      context: . 
    env_file:
      - .env
    ports: 
      - 3001:3000
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: maindb
    ports:
      - 8001:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin 
      ME_CONFIG_MONGODB_URL: mongodb://root:admin@mongodb:27017/
    depends_on:
      - mongodb